apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent
  template:
    metadata:
      labels:
        app: agent
    spec:
      containers:
        - name: agent
          image: vigil-agent:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: vigil-config
            - secretRef:
                name: vigil-secret
