apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
        - name: notifier
          image: vigil-notifier:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2112
          envFrom:
            - configMapRef:
                name: vigil-config
            - secretRef:
                name: vigil-secret
