// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: alert.proto

package metric

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertState int32

const (
	AlertState_ALERT_STATE_UNSPECIFIED AlertState = 0
	AlertState_ALERT_STATE_FIRING      AlertState = 1
	AlertState_ALERT_STATE_RESOLVED    AlertState = 2
)

// Enum value maps for AlertState.
var (
	AlertState_name = map[int32]string{
		0: "ALERT_STATE_UNSPECIFIED",
		1: "ALERT_STATE_FIRING",
		2: "ALERT_STATE_RESOLVED",
	}
	AlertState_value = map[string]int32{
		"ALERT_STATE_UNSPECIFIED": 0,
		"ALERT_STATE_FIRING":      1,
		"ALERT_STATE_RESOLVED":    2,
	}
)

func (x AlertState) Enum() *AlertState {
	p := new(AlertState)
	*p = x
	return p
}

func (x AlertState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertState) Descriptor() protoreflect.EnumDescriptor {
	return file_alert_proto_enumTypes[0].Descriptor()
}

func (AlertState) Type() protoreflect.EnumType {
	return &file_alert_proto_enumTypes[0]
}

func (x AlertState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertState.Descriptor instead.
func (AlertState) EnumDescriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{0}
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Metric        string                 `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Threshold     float64                `protobuf:"fixed64,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	State         AlertState             `protobuf:"varint,6,opt,name=state,proto3,enum=alert.AlertState" json:"state,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alert_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Alert) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Alert) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Alert) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Alert) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *Alert) GetState() AlertState {
	if x != nil {
		return x.State
	}
	return AlertState_ALERT_STATE_UNSPECIFIED
}

func (x *Alert) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_alert_proto protoreflect.FileDescriptor

const file_alert_proto_rawDesc = "" +
	"\n" +
	"\valert.proto\x12\x05alert\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x01\n" +
	"\x05Alert\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x16\n" +
	"\x06metric\x18\x03 \x01(\tR\x06metric\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x01R\tthreshold\x12'\n" +
	"\x05state\x18\x06 \x01(\x0e2\x11.alert.AlertStateR\x05state\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*[\n" +
	"\n" +
	"AlertState\x12\x1b\n" +
	"\x17ALERT_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ALERT_STATE_FIRING\x10\x01\x12\x18\n" +
	"\x14ALERT_STATE_RESOLVED\x10\x02B&Z$github.com/honnek/vigil/proto;metricb\x06proto3"

var (
	file_alert_proto_rawDescOnce sync.Once
	file_alert_proto_rawDescData []byte
)

func file_alert_proto_rawDescGZIP() []byte {
	file_alert_proto_rawDescOnce.Do(func() {
		file_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)))
	})
	return file_alert_proto_rawDescData
}

var file_alert_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_alert_proto_goTypes = []any{
	(AlertState)(0),               // 0: alert.AlertState
	(*Alert)(nil),                 // 1: alert.Alert
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_alert_proto_depIdxs = []int32{
	0, // 0: alert.Alert.state:type_name -> alert.AlertState
	2, // 1: alert.Alert.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_alert_proto_init() }
func file_alert_proto_init() {
	if File_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_alert_proto_rawDesc), len(file_alert_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_alert_proto_goTypes,
		DependencyIndexes: file_alert_proto_depIdxs,
		EnumInfos:         file_alert_proto_enumTypes,
		MessageInfos:      file_alert_proto_msgTypes,
	}.Build()
	File_alert_proto = out.File
	file_alert_proto_goTypes = nil
	file_alert_proto_depIdxs = nil
}
