// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: anomaly.proto

package metric

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Anomaly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	MetricName    string                 `protobuf:"bytes,2,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Mean          float64                `protobuf:"fixed64,4,opt,name=mean,proto3" json:"mean,omitempty"`
	StdDev        float64                `protobuf:"fixed64,5,opt,name=std_dev,json=stdDev,proto3" json:"std_dev,omitempty"`
	Zscore        float64                `protobuf:"fixed64,6,opt,name=zscore,proto3" json:"zscore,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anomaly) Reset() {
	*x = Anomaly{}
	mi := &file_anomaly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anomaly) ProtoMessage() {}

func (x *Anomaly) ProtoReflect() protoreflect.Message {
	mi := &file_anomaly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anomaly.ProtoReflect.Descriptor instead.
func (*Anomaly) Descriptor() ([]byte, []int) {
	return file_anomaly_proto_rawDescGZIP(), []int{0}
}

func (x *Anomaly) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Anomaly) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Anomaly) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Anomaly) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *Anomaly) GetStdDev() float64 {
	if x != nil {
		return x.StdDev
	}
	return 0
}

func (x *Anomaly) GetZscore() float64 {
	if x != nil {
		return x.Zscore
	}
	return 0
}

func (x *Anomaly) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Anomaly) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_anomaly_proto protoreflect.FileDescriptor

const file_anomaly_proto_rawDesc = "" +
	"\n" +
	"\ranomaly.proto\x12\aanomaly\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x01\n" +
	"\aAnomaly\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1f\n" +
	"\vmetric_name\x18\x02 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x12\n" +
	"\x04mean\x18\x04 \x01(\x01R\x04mean\x12\x17\n" +
	"\astd_dev\x18\x05 \x01(\x01R\x06stdDev\x12\x16\n" +
	"\x06zscore\x18\x06 \x01(\x01R\x06zscore\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x128\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB&Z$github.com/honnek/vigil/proto;metricb\x06proto3"

var (
	file_anomaly_proto_rawDescOnce sync.Once
	file_anomaly_proto_rawDescData []byte
)

func file_anomaly_proto_rawDescGZIP() []byte {
	file_anomaly_proto_rawDescOnce.Do(func() {
		file_anomaly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anomaly_proto_rawDesc), len(file_anomaly_proto_rawDesc)))
	})
	return file_anomaly_proto_rawDescData
}

var file_anomaly_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_anomaly_proto_goTypes = []any{
	(*Anomaly)(nil),               // 0: anomaly.Anomaly
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_anomaly_proto_depIdxs = []int32{
	1, // 0: anomaly.Anomaly.timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_anomaly_proto_init() }
func file_anomaly_proto_init() {
	if File_anomaly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anomaly_proto_rawDesc), len(file_anomaly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_anomaly_proto_goTypes,
		DependencyIndexes: file_anomaly_proto_depIdxs,
		MessageInfos:      file_anomaly_proto_msgTypes,
	}.Build()
	File_anomaly_proto = out.File
	file_anomaly_proto_goTypes = nil
	file_anomaly_proto_depIdxs = nil
}
