// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: log.proto

package metric

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogIngest_StreamLogs_FullMethodName = "/log.LogIngest/StreamLogs"
)

// LogIngestClient is the client API for LogIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogIngestClient interface {
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, LogStreamSummary], error)
}

type logIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewLogIngestClient(cc grpc.ClientConnInterface) LogIngestClient {
	return &logIngestClient{cc}
}

func (c *logIngestClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, LogStreamSummary], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogIngest_ServiceDesc.Streams[0], LogIngest_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEntry, LogStreamSummary]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogIngest_StreamLogsClient = grpc.ClientStreamingClient[LogEntry, LogStreamSummary]

// LogIngestServer is the server API for LogIngest service.
// All implementations must embed UnimplementedLogIngestServer
// for forward compatibility.
type LogIngestServer interface {
	StreamLogs(grpc.ClientStreamingServer[LogEntry, LogStreamSummary]) error
	mustEmbedUnimplementedLogIngestServer()
}

// UnimplementedLogIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogIngestServer struct{}

func (UnimplementedLogIngestServer) StreamLogs(grpc.ClientStreamingServer[LogEntry, LogStreamSummary]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLogIngestServer) mustEmbedUnimplementedLogIngestServer() {}
func (UnimplementedLogIngestServer) testEmbeddedByValue()                   {}

// UnsafeLogIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogIngestServer will
// result in compilation errors.
type UnsafeLogIngestServer interface {
	mustEmbedUnimplementedLogIngestServer()
}

func RegisterLogIngestServer(s grpc.ServiceRegistrar, srv LogIngestServer) {
	// If the following call panics, it indicates UnimplementedLogIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogIngest_ServiceDesc, srv)
}

func _LogIngest_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogIngestServer).StreamLogs(&grpc.GenericServerStream[LogEntry, LogStreamSummary]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogIngest_StreamLogsServer = grpc.ClientStreamingServer[LogEntry, LogStreamSummary]

// LogIngest_ServiceDesc is the grpc.ServiceDesc for LogIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log.LogIngest",
	HandlerType: (*LogIngestServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _LogIngest_StreamLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "log.proto",
}

const (
	LogsQuery_QueryLogs_FullMethodName = "/log.LogsQuery/QueryLogs"
)

// LogsQueryClient is the client API for LogsQuery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogsQueryClient interface {
	QueryLogs(ctx context.Context, in *LogQuery, opts ...grpc.CallOption) (*LogQueryResult, error)
}

type logsQueryClient struct {
	cc grpc.ClientConnInterface
}

func NewLogsQueryClient(cc grpc.ClientConnInterface) LogsQueryClient {
	return &logsQueryClient{cc}
}

func (c *logsQueryClient) QueryLogs(ctx context.Context, in *LogQuery, opts ...grpc.CallOption) (*LogQueryResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogQueryResult)
	err := c.cc.Invoke(ctx, LogsQuery_QueryLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogsQueryServer is the server API for LogsQuery service.
// All implementations must embed UnimplementedLogsQueryServer
// for forward compatibility.
type LogsQueryServer interface {
	QueryLogs(context.Context, *LogQuery) (*LogQueryResult, error)
	mustEmbedUnimplementedLogsQueryServer()
}

// UnimplementedLogsQueryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogsQueryServer struct{}

func (UnimplementedLogsQueryServer) QueryLogs(context.Context, *LogQuery) (*LogQueryResult, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryLogs not implemented")
}
func (UnimplementedLogsQueryServer) mustEmbedUnimplementedLogsQueryServer() {}
func (UnimplementedLogsQueryServer) testEmbeddedByValue()                   {}

// UnsafeLogsQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogsQueryServer will
// result in compilation errors.
type UnsafeLogsQueryServer interface {
	mustEmbedUnimplementedLogsQueryServer()
}

func RegisterLogsQueryServer(s grpc.ServiceRegistrar, srv LogsQueryServer) {
	// If the following call panics, it indicates UnimplementedLogsQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogsQuery_ServiceDesc, srv)
}

func _LogsQuery_QueryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogsQueryServer).QueryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LogsQuery_QueryLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogsQueryServer).QueryLogs(ctx, req.(*LogQuery))
	}
	return interceptor(ctx, in, info, handler)
}

// LogsQuery_ServiceDesc is the grpc.ServiceDesc for LogsQuery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogsQuery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "log.LogsQuery",
	HandlerType: (*LogsQueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryLogs",
			Handler:    _LogsQuery_QueryLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "log.proto",
}
